import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import { i18n } from './i18n';
import { router } from './router';
import './styles/main.css';
import './styles/history.css';
import './styles/assistant.css';
import './styles/visitor-twin.css';
import './styles/results.css';
createApp(App).use(createPinia()).use(i18n).use(router).mount('#app');
