<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { api } from '../api'; import DiagnosisEvidence from '../components/DiagnosisEvidence.vue'; import { useDiagnosisStore } from '../stores/diagnosis'
const { t } = useI18n(); const diagnosis = useDiagnosisStore(); const loading = ref(false); const result = ref<any>(null); const error = ref(false); const history = ref<any[]>([])
function signal() { return Array.from({length: 2048}, (_, i) => .24*Math.sin(i*.17) + (i%137===0 ? 1.4 : 0)) }
async function loadHistory() { history.value = await api('/diagnosis/history?limit=8') }
async function run() { loading.value=true; error.value=false; try { result.value=await api('/diagnosis/predict',{method:'POST',body:JSON.stringify({samples:signal(),sampling_rate:25600,model_id:'hpsu-dan-v1'})}); diagnosis.applyResult(result.value); await loadHistory() } catch { error.value=true } finally { loading.value=false } }
onMounted(() => loadHistory().catch(() => undefined))
</script>
<template><section><div class="page-title"><div><p class="eyebrow">AI DIAGNOSIS / INTEGRATION</p><h1>{{ t('diagnosis.title') }}</h1><p>{{ t('diagnosis.description') }}</p></div><button class="primary action" :disabled="loading" @click="run">{{ loading?t('diagnosis.running'):t('diagnosis.run') }}</button></div><p v-if="error" class="error-box">{{ t('diagnosis.unavailable') }}</p><div v-if="result" class="result-grid"><article class="result-main glass-panel"><p class="eyebrow">{{ t('diagnosis.result') }}</p><h2>{{ $i18n.locale==='zh-CN'?diagnosis.current.labelZh:diagnosis.current.labelEn }}</h2><div class="score-row"><div><small>{{ t('diagnosis.confidence') }}</small><strong>{{ (diagnosis.current.confidence*100).toFixed(1) }}%</strong></div><div><small>{{ t('diagnosis.health') }}</small><strong>{{ diagnosis.current.healthScore }}</strong></div></div><p class="warning-text">{{ $i18n.locale==='zh-CN'?diagnosis.current.suggestionZh:diagnosis.current.suggestionEn }}</p></article><article class="glass-panel topk"><p class="eyebrow">TOP-K</p><div v-for="item in result.topk" :key="item.label"><span>{{ $i18n.locale==='zh-CN'?item.label_zh:item.label_en }}</span><b>{{ (item.probability*100).toFixed(1) }}%</b></div><code>target={{ diagnosis.current.twinTarget }}</code><code>engine_mode={{ result.engine_mode }}</code></article></div><DiagnosisEvidence :waveform-mode="diagnosis.current.waveformMode" :markers="diagnosis.current.spectrumMarkers" :waveform="diagnosis.current.waveformPoints" :spectrum="diagnosis.current.spectrumPoints"/><article class="glass-panel history-card"><p class="eyebrow">{{ t('diagnosis.history') }}</p><div class="history-row history-head"><span>ID</span><span>{{ t('diagnosis.operator') }}</span><span>MODEL</span><span>{{ t('diagnosis.confidence') }}</span></div><div v-for="item in history" :key="item.task_id" class="history-row"><code>{{ item.task_id.slice(-12) }}</code><span>{{ item.requested_by }}</span><span>{{ item.label }}</span><b>{{ (item.confidence*100).toFixed(1) }}%</b></div></article></section></template>

